name: Publish peaq SDK to PyPI and TestPyPI

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      version:
        description: 'Version Type to Bump (major, minor, patch)'
        required: true
        default: 'patch'
  push:
    branches:
      - dev 

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install bump2version
        if: ${{ github.event_name == 'workflow_dispatch' }}  # Only run this job when manually triggered
        run: pip install bump2version
      - name: Bump version
        run: |
          # Get the version bump type (major, minor, patch) from the input
          if ${{ github.event_name == 'workflow_dispatch' }} ; then
           bump2version ${{ github.event.inputs.version }} --no-tag --config-file bumpversion.cfg 
           #reset dev version to current release version
           VERSION=$(python -c "import configparser; config = configparser.ConfigParser(); config.read('setup.cfg'); print(config['metadata']['version'])")
           sed -i "/\[development\]/,/^\[/{s/^version = .*/version = $VERSION/}" setup.cfg

          else
           VERSION=$(python -c "import configparser; config = configparser.ConfigParser(); config.read('setup.cfg'); print(config['development']['version'])")
           echo "Current version: $VERSION"
          # If the version doesn't already have a .dev suffix, append '.dev1'
           if [[ "$VERSION" != *".dev"* ]]; then
             BASE_VERSION=$VERSION
             DEV_VERSION=1
           else
             # If the version already has a .devX suffix, increment the X part
             BASE_VERSION=$(echo $VERSION | sed 's/\(.*\)\.dev[0-9]\+/\1/')  # Strip current .devX part
             DEV_VERSION=$(echo $VERSION | sed 's/.*\.dev\([0-9]\+\)/\1/')  # Extract current dev number
             DEV_VERSION=$((DEV_VERSION + 1))  # Increment dev number
           fi
          # Construct the new version (e.g., 0.0.1 -> 0.0.1.dev1, 0.0.1.dev1 -> 0.0.1.dev2)
           NEW_VERSION="$BASE_VERSION.dev$DEV_VERSION"
           echo "Bumping version to $NEW_VERSION"
          # Update the version in setup.cfg
           sed -i "/\[development\]/,/^\[/{s/^version = .*/version = $NEW_VERSION/}" setup.cfg

          # Output the new version for further steps
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          fi
      - name: Push version bump changes
        run: |
           git config --global user.name "github-actions"
           git config --global user.email "github-actions@github.com"
           git add setup.cfg
           git commit -m "Bump version to $NEW_VERSION"
           git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
  build:
    name: Build distribution
    needs: bump_version
    if: ${{ github.actor != 'peaqbot' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        persist-credentials: false
    - name: Set release version for TestPypi
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
         VERSION=$(python -c "import configparser; config = configparser.ConfigParser(); config.read('setup.cfg'); print(config['development']['version'])")
          sed -i "s/^version = .*/version = $VERSION/" setup.cfg
          echo "Using release version: $VERSION"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python  distribution  to PyPI
    if: ${{ github.event_name == 'workflow_dispatch' }}  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/peaq-sdk 
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: >-
      Sign the Python distribution with Sigstore
      and upload them to GitHub Release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  
      id-token: write  
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        "$GITHUB_REF_NAME"
        --repo "$GITHUB_REPOSITORY"
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release upload
        "$GITHUB_REF_NAME" dist/**
        --repo "$GITHUB_REPOSITORY"

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/peaq-sdk

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true